### ISSUE TITLE
[Feature] Home Page (Implementation)

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#105]
**Describe new addition**
Implement the home page for new ACM Portal.

**Task List**
 - [x] Replicate Figma mockup. Should include the following
     - [x] Name of logged in user
     - [x] NetID
     - [x] User's attended events
 - [x] Should be both desktop and mobile friendly
 
**Additional context**
N/A
