### ISSUE TITLE
[Feature] Generate Check-in URL

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#118]
**Describe new addition**
Portal-v2 currently doesn't have a way for officer to acquire check-in link for an event, so implementation for generating check-in URL is needed. Check-in url will have the following format: `https://{base_url}/checkin/{event_id}`, which is equivalent to the file `pages/checkin/[slug].tsx` file. 

**Task List**
 - [x] Fetch the id of the event when querying data for Events page. 
 - [x] Upon clicking the event card, **only officers** should be able to see a button that upon clicking will display the check-in url. 
 - [x] **Optional**: Generate a QR code that upon scanning will redirect to check-in URL (can use [this](https://www.npmjs.com/package/jsqr) for QR code generator)

**Additional context**
N/A
