### ISSUE TITLE
[Feature] Incorporate division info into a Typeform Application

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#125]
**Describe new addition**
Currently, when accessing the "apply" page, one can notice that all applications hardcoded as belonging to "development" division, so there needs to be a way to specify which division owns which application. 

**Task List**
**1. Backend**
 - [x] Add an extra field called `division` into `TypeformApplication` model to allow storing division info in `schema.prisma`. 
 - [x] Run `prisma db push` to synchronize database with schema. 

**2. Frontend**
 - [x] Inside the form to create a new Typeform application, add a new dropdown input to allow officers to specify which division the application belongs to. 
 - [x] Update state variable to contain new information. 
 - [x] When go to "apply" page, the division name on top of each application card should match the data stored in the new attribute. 

**Additional context**
N/A
