### ISSUE TITLE
[Feature] Make user aware about confirmation email. 

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#127]
**Describe new addition**
Currently, after creating application, profile, and events, confirmation email will be sent to users, but there is no mechanism to help user aware of such a fact. 

**Task List**
 - [x] Alert user that confirmation email will be sent shortly upon creating application, profile, and events. The alert can be accomplished by either of the following: 
     - [ ] [React Toastify](https://www.npmjs.com/package/react-toastify )
     - [x] [MUI Snackbar](https://mui.com/material-ui/react-snackbar/ )
     - [ ] Simple `alert` function.  
       - [x] Create application
       - [x] Create profile
       - [x] Create event
 - [x] If either Toastify or Snackbar is used, make sure that it is a component for reusability. 

**Additional context**
- To enable email-sending logic execution, go [here](https://github.com/acmutd/portal-next/blob/next/apps/portal/pages/api/graphql/index.ts#L20) and make the if statement always evaluated to true. 
- To make yourself an officer, go to Profile -> Edit -> Connect Account -> Connect with ACM Account, and login with your ACM account.
