### ISSUE TITLE
[Feature] UI/UX Improvement for Create Typeform Application page

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#129]
**Describe new addition**
Currently, the UI for the Create Typeform Application page is rather barebone and that there is no specific information regarding what kind of information goes to each input box. 

**Task List**
Following is a list of what I think are the changes needed for this page. Note that this list can be extended in any way that one sees fit: 
- [ ] Add more description in terms of what kind of information is expected for each input box. (refer to Figma for more details).  
- [ ] Improve layout for status checkbox in Typeform Edit form.  
- [ ] `status` should be hidden in `Typeform Create` form and has its default value as `true`, as a newly-created form should be visible by default. 
- [ ] **Optional**: If possible, combine the `Typeform Create` and `Typeform Edit` render logic into 1 function instead of 2 separate functions, since what they render is rather similar to each other. 

**Additional context**
- [Figma Mockup](https://www.figma.com/file/hcWO0N1DdSwFFIykbks0n7/Member-Portal-v2?node-id=422%3A1063&t=Go6OqFNQ9cm4jY5j-0)
- `status` checkbox in the form is used to specify whether the typeform will be displayed on portal. 
- [Typeform Create component](https://github.com/acmutd/portal-next/blob/next/apps/portal/components/typeformApplicationSystem/update-application-form.tsx#L142)
- [Typeform Edit component](https://github.com/acmutd/portal-next/blob/next/apps/portal/components/typeformApplicationSystem/update-application-form.tsx#L36)
