### ISSUE TITLE
[Feature] Big issue for Kevin 🤠

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#142]
**Describe new addition**
One big issue just for Kevin. 

**Task List**
 - [ ] Hide the “Click to view QR Code” if user is not officer. 
     - [ ] Only officer can have access the QR code page.  
 - [ ] Change logo of "Sign Out" button in mobile navbar into something else. 
 - [ ] Fix desktop navbar highlight error. 
     - [ ] This can be fixed by adding the `$active` prop [here](https://github.com/acmutd/portal-next/blob/next/apps/portal/components/Skeleton.tsx#L83). The `$active` prop usage can be referred [here](https://github.com/acmutd/portal-next/blob/next/apps/portal/components/Skeleton.tsx#L94-L106)
 - [ ] Fix button text overlap mobile navbar. 

**Some screenshot about the error**
Button text overlap error
![Capture](https://user-images.githubusercontent.com/34334226/219567081-459a1d43-ac38-44ce-b471-ec8d9e6d63c5.PNG)
