### ISSUE TITLE
[Feature] User View for New Application System

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#149]
**Describe new addition**
React implementation for user view of the new application system for portal-v2. 

**Task List**
 - [x] Fetch open application view. 
 - [x] Fetch all applications submitted by a user. 
 - [x] Populate view with data from backend (defer until backend is completed). 

**Additional context**
[Figma Mockup](https://www.figma.com/file/hcWO0N1DdSwFFIykbks0n7/Member-Portal-v2?node-id=1701%3A2460&t=7ctVgs5Gm3tKMqgh-0)
