### ISSUE TITLE
[Feature] Implement Admin View for specific application

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#159]
**Describe new addition**
Admin view for specific application needs to be implemented. Mockup can be found in screenshot below: 
![Capture](https://user-images.githubusercontent.com/34334226/228418665-c573c8c5-9616-4b14-a102-cf81f864a7eb.PNG)

**Task List**
- [ ] Implement Search box to filter applicants based on their name and netID
- [ ] Implement Dropdown to filter by class standing, application status, and preference. 
- [ ] `Notes` and `Application Question` section should be rendered dynamically based on chosen applicant in the list on bottom left. 
- [ ] Applicant list should be scrollable 

**Additional context**
- [Figma Link](https://www.figma.com/file/hcWO0N1DdSwFFIykbks0n7/Member-Portal-v2?node-id=1701-2460&t=SfFLbphQHtQ3i1qw-0)
- [Example on search box debounce logic](https://github.com/acmutd/hackportal/blob/develop/pages/admin/users.tsx#L60-L79)
- [Example on search box implementation](https://github.com/acmutd/hackportal/blob/develop/pages/admin/users.tsx#L132-L139)

**Useful Component Library (if needed)**
- [daisyUI](https://daisyui.com/)
- [Radix UI](https://www.radix-ui.com/docs/primitives/overview/getting-started)
