### ISSUE TITLE
[Internal] Improve Error Handling Infrastructure

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#160]
**Describe the issue**
Currently, upon encountering any error, React implementation will simply either call `alert` or simply `console.log` the error object. Also, the current custom error object being used in the backend is limited as it does not allow returning custom error code. 

**Task List**
- [x] Improve error handling on the backend.
    - [x] Change all usages of `CombinedError` in all middlewares in `lib/graphql/middlewares` into `GraphQLError`, which supports custom error code (refer to resource in Additional Context section for more details).  
    - [x] Create custom error code for all known error from the backend, following is some example:
        - [x] netID already exists (refer to  `lib/graphql/middlewares/check-netid.ts` for more details). 
        - [x] Login required.  
        - [x] Profile does not exist.
    - [ ] **Optional**: Look into integration with Sentry.  
- [x] Improve error handling on the frontend. 
    - [x] Use `ErrorComponent` instead of simply printing out the error like [this](https://github.com/acmutd/portal-next/blob/next/pages/index.tsx#L95). 
    - [x] If needed, refactor `ErrorComponent` to accept custom error code as parameter and handle it internally. 
    - [x] If an unknown error is encountered (i.e any error that either does not have a custom error or any error that has a generic error code), configure the `ErrorComponent` to show the whole error object and tell user to contact developers for help. 

**Additional Context**
- [GraphQLError](https://www.apollographql.com/docs/apollo-server/data/errors/#custom-errors)
- [ErrorComponent](https://github.com/acmutd/portal-next/blob/next/components/ErrorComponent.tsx)
