### ISSUE TITLE
[Feature] Budget Dashboard

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#180]
**Describe new addition**
We need a dashboard that is only accessible by division's directors so that they can keep track of budget for their division. 

**Task List**
 - [x] Propose database modification
 - [x] Implement script to update database with most updated budget value
 - [x] Implement UI to display data from backend

**Additional context**
Requires #179 to be done first.
