### ISSUE TITLE
[Internal] Restrict GraphQL resolver access

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#223]
**Describe the issue**
We need to apply some restrictions to some of the GraphQL resolvers. 

**Task List**
- Restrict access to the following resolvers to director only: 
    - [x] officerEligibleProfile (this is a manually-implemented resolver)
    - [x] addUserToDivision (this is a manually-implemented resolver)
    - [x] createOneTypeformApplication (this is an auto-generated resolver)
- Restrict access to the following resolvers to officer only: 
    - [x] createOneEvent (this is an auto-generated resolver)
    - [x] createOneVanityLink (this is an auto-generated resolver)
- Only let requests to the following mutation pass through if request initiator owns the data being modified: 
    - [x] profile (FindUniqueProfileResolver)
    - [x] checkInOldEvent
    - [x] checkInToEvent  

**Additional Context**
- The easiest way to reject an unauthorized request to a resolver would be through using [a middleware](https://typegraphql.com/docs/middlewares.html)
- To apply a middleware to an auto-generated resolver, refer to [this file](https://github.com/acmutd/portal-next/blob/next/lib/graphql/typegraphql-prisma/enhancer.ts) and [guide](https://prisma.typegraphql.com/docs/advanced/additional-decorators). 
- To apply a middleware to a manually-implemented resolver, refer to [this guide](https://typegraphql.com/docs/middlewares.html#attaching-middleware)
- List of middlewares already available for use can be found [here](https://github.com/acmutd/portal-next/tree/next/lib/graphql/middlewares). 
- To test a middleware on a auto-generated resolver, make sure to disable [this if statement](https://github.com/acmutd/portal-next/blob/next/pages/api/graphql/index.ts#L29).
