### ISSUE TITLE
[Feature] Profile Page UI Improvement

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#243]
**Describe new addition**
Improve the UI for profile page. 

**Task List**
- [x] #251
- [x] Add border around "edit" button. 
- [x] Change "edit" button to "setup profile" is profile is not created yet. 
- [x] Hide Mr. Peechi on mobile view when in edit mode.  

**Additional context**
N/A
