### ISSUE TITLE
Enhanced Event Editing

### ISSUE THREAD

**Issue by shoaibhuq** [acmutd/portal-next#260]
**Event Editing**
When editing events in portal, create a way of keeping track of the event through an event ID. That way when someone updates the event information (dates, name, time, description) it updates in the discord and google calendar as well.

**Task List**
- [ ]  - Add event IDs to each event for tracking
- [ ]  - Update google calendar event with new information (when edited)
- [ ]  - Update discord event with new information (when edited)
- [ ]  - Test and make sure there are no bugs in the editing process
- [ ]  - (Optional) Add a buffer just in case multiple edits are happening to the same event within a short period of time

 
 
<img width="836" alt="image" src="https://github.com/user-attachments/assets/083a683a-b661-49fe-bfa3-1c3224d427db">
