### ISSUE TITLE
[Feature] Authentication & Roles

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#39]
**Describe new addition**
We need to finish up the authentication system for users to log in, from which we can then use to assign roles to users based on whether they are officers or not. 

**Task List**
Following is what I think needs to be done to finish this feature: 
 - [x] Connect Cognito with Next-Auth
 - [x] Portal needs to be able to support the following role by the end of Summer: **officer**, **user**
 - [x] Gives officer role to those login with ACM Account

**Additional context**
Following is some resources that I think might be useful for working on this feature: 
- [Connect Next-Auth with Cognito](https://next-auth.js.org/providers/cognito)
- [Next-Auth callbacks (might be useful for assigning roles)](https://next-auth.js.org/configuration/callbacks)
