### ISSUE TITLE
[Feature] Application System (Implementation)

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#42]
**Describe new addition**
We need a system that allows officers from to create application for semester-long programs such as Projects, Research, and TIPs. For now, the current plan is to implement a flow that allows officers to connect Portal with a pre-created Typeform. This issue will focus on what needs to be done to have a functional **ReactJS implementation** for the application system.

**Task List**
Following is what I think needs to be accomplished for Portal to have a functional **ReactJS implementation** for application system.
 - [x] UI for creating typeform applications using mockups
 - [x] Connect UI to backend
 - [x] Fetch & render the appropriate Typeform for users to fill out application
 

**Additional context**
The application system that we are trying to create by the end of this Summer is similar to what the previous version of Portal is doing, hence some logic in the old Portal can be reused for this feature. 

Additionally, since we plan to move towards our own application system, the implementation should be done in a way such that changing from Typeform application to our own system requires minimal work.
