### ISSUE TITLE
[Feature] CRUD Event (Mockup)

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#44]
**Describe new addition**
We need a system that allows officers and users to interact with our database of events. This issue will focus on what needs to be done to have a **UI Mockup** for the Event CRUD system.

**Task List**
Following is what I think is necessary to accomplish this feature: 
 - [x] UI View listing all upcoming events
   - [x] With graphic
   - [x] Without graphic  
 - [x] UI View for viewing details for one specific event
 - [x] UI View listing all attended events

**Additional context**
N/A

**Comment by DedsecKnight** [comment]
Closing issue because mockup is completed.
