### ISSUE TITLE
[Feature] CRUD Event (Implementation)

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#45]
**Describe new addition**
We need a system that allows officers and users to interact with our database of events. This issue will focus on what needs to be done to have a functional **ReactJS implementation** for the Event CRUD system.

**Task List**
Following is what I think needs to be done to accomplish this feature: 
 - [x] UI View for listing all upcoming events
   - [ ] With graphic
   - [x] Without graphic  
 - [x] UI View for viewing details for one specific event
 - [x] UI list all attended events
- [x] Redirect back to events page after submitting event creation form. 

**Additional context**
N/A
