### ISSUE TITLE
[Feature] Event Check-in (Implementation)

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#47]
**Describe new addition**
We need a system that allows users to rsvp/check-in into an event. This issue will focus on what needs to be done to have a functional **ReactJS implementation** for the Event Check-in system.

**Task List**
Following is what I think needs to be done to accomplish this feature: 
 - [x] Have a frontend endpoint for user to access to check-in (something like `portal.acmutd.co/events/event-id`). 
 - [x] Verify user identity on access the endpoint
     - [x] If user haven't logged in, redirect them back to `auth/signin` 
 - [x] Retrieve user and event ID, and send them to backend. 
 - [x] On successful, redirect users back to Events page. 

**Additional context**
N/A
