### ISSUE TITLE
[Feature] CRUD Profile (Implementation)

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#49]
**Describe new addition**
We need a system that allows users to interact with their profile data. This issue will focus on what needs to be done to have a functional **ReactJS implementation** for the Event Check-in system.

**Task List**
Following is what I think needs to be done to accomplish this feature:
 - [x] UI displaying a person's profile
 - [x] UI for editing profile
 - [x] Redirect user to create a new profile on first time logging in. 

**Additional context**
N/A
