### ISSUE TITLE
[Feature] Authorization

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#50]
**Describe new addition**
This issue will focus on what needs to be done to make sure that Portal users can only perform actions that they are allowed to (e.g: normal users are not allowed to perform officers-only functionalities).

**Task List**
Following is what I think needs to be done to accomplish this feature: 
 - [x] Create a TypeGraphQL middleware function to restrict operation to user(s) with matching identifier. 
 - [x] Create a TypeGraphQL middleware function to restrict operation to officers only. 
 - [x] Application System
   - [x] Only officers can create / edit / update / delete applications from Portal. 
 - [x] CRUD Event
   - [x] Only officers can create / edit / delete events.  
 - [x] Event Check-in
   - [x] User can only check themselves in.  
 - [x] Profile
   - [x] User can only edit their own profile.  

**Additional context**
From my knowledge, most of the work done to accomplish this feature will be on implementing the 2 middleware functions. After that, it is rather straightforward to attach the middleware into the generated resolvers using the attached resource. 

Additionally, the following resources may be useful for implementing this feature: 
- [Implementing a middleware function in TypeGraphQL](https://typegraphql.com/docs/middlewares.html#creating-middleware)
- [Attaching a middleware function into a resolver generated by TypeGraphQL-Prisma](https://prisma.typegraphql.com/docs/advanced/additional-decorators/)
- [Attaching a middleware function into a custom resolver](https://typegraphql.com/docs/middlewares.html#attaching-middleware)

**Comment by stevenmqnguyen** [comment]
[graphql shield](https://www.graphql-shield.com/docs) provides an easy to use authorization middleware, which lets us create a collection of rules, and even apply per field or per type permissions.
