### ISSUE TITLE
[Feature] Frontend Components

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#51]
**Describe new addition**
This issue will focus on a few stuffs that need to be done on the frontend of Portal. 

**Task List**
 - [x] Dependencies
   - [x] remove Storybook 
 - [ ] Create components for common UI elements (navbar, buttons, etc) and store it inside `@acmutd/acm-ui`
   - [x] ACMButton
     - [ ] Set width to be able to handle other units (outside of px)
   - [x] ACMNavbar
     - [x] Make sure it matches designs and works on both mobile and PC. Idea is to plop in into the page and itll attach itself to the side / bottom automatically
   - [x] ACMNavbarElement
     - [x] Passed into ACMNavbar, clickable like ACMButton. Might need to extract link logic into an abstract wrapper element for both this and Button, but prolly not necessary for now. Basically a specialized ACMButton with different styling specifically for navbar
   - [x] ACMCard
     - [x] Just a wrapper element for text. Make it matches designs and make sure you can wrap it with styled-components and styles are applied to child divs with text
   - [ ] ACMLogo
     - [ ] Drag and Drop element for the acm logo, could contain multiple selectable styles
   - [ ] ACMDivisionLogo
     - [ ] Drag and drop wrapper element for division logos, specify which division with a prop
 - [ ] Documentation for Components
   - [ ] Description
   - [ ] Examples (screenshots) 

**Additional context**
N/A

**Comment by DedsecKnight** [comment]
@trexrush I am not 100% sure on the intention of this part so I'd appreciate it if you can add more details in what we're trying to accomplish with this issue.
