### ISSUE TITLE
[Internal] [Fall] Call acm-ui components from library instead of source

### ISSUE THREAD

**Issue by trexrush** [acmutd/portal-next#61]
**Describe the issue**
Components in the acm-ui are not being pulled from the rollup build of the package, but rather from the source code itself. This is a temporary solution as a result of a build error from using emotion to style components with css-in-js that caused a hook misuse error.

**Task List**
 - [x] Correctly pull components from a rollup-generated (or other compilation) file. 1 of 2 solutions I can think of:
 - - [x] fix the error that causes components pulled from the build to fail, or
 - - [x] Use another builder than rollup / another css-in-js library than emotion
 - [x] Fix any changes that might occur as a result of moving component source locations

 - [x] (optional) Possibly analyze the performance impact of the solution?

**Additional Context**
The initial goal of the component library was to be able to deploy to a package repository like NPM to have ACM use a consistent set of UI features, but due to complications that is not the current way it is being used.

**Comment by trexrush** [comment]
resolved
