### ISSUE TITLE
[Feature] Event Header

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#71]
**Describe new addition**
The header of the Event page consist of a button that should toggle the edit state of the event pages when being clicked. Since the header itself is intended to be a component and overall state management should be delegated to the page itself, there should be a way for the header component to communicate with the events page. 

**Proposed approach**
The props of the Header component should have the following interface (this could be re-designed in any way that the developer deems fit): 
```ts
interface EventPageHeaderProps {
    isInEditMode: boolean;
    toggleEdit: () => void;
}
``` 
In the proposed approach, `isInEditMode` is a boolean flag that will be used to render what is appeared on the Edit button. The prop `toggleEdit` will be a void function that will be called when clicking the edit button. The header component just needs to call the `toggleEdit` function when the `Edit` button is clicked. 
 
**Task List**
 - [x] Create a `EventHeader.tsx` file in `apps/portal/components` that will render the Header component. 
 - [x] Make sure that the component is able to notify the events page when the `Edit` button is clicked so that the events page can update the state management properly. 
     - [x] If decides to follow proposed approach, that will be making sure that the `toggleEdit` function will be called when `Edit` button is clicked.  
 - [x] Make sure that the component is able to receive the state of the page from the events page. 
     - [x] If decides to follow proposed approach, that will be making sure that the button state is rendered properly using the `isInEditMode` flag. 
     
**Additional context**
N/A
