### ISSUE TITLE
[Feature] Add restriction to GraphQL endpoint

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#75]
**Current Issue**
Currently, anyone can make queries to member portal's GraphQL server through the `/api/graphql` endpoint, especially when most of the TypeGraphQL-Prisma generated resolvers do not have any authorization or whatsoever. 

**Proposed Solution**
One way that I think we can mitigate this is to only expose the resolvers that Portal needs to be able to interact with the database and then apply appropriate authorization on each exposed resolvers through middlewares. 

With that said, any other solutions are welcome. 

**Task List for Proposed Solution**
If decided to follow the proposed solution, the following is what I think are needed to accomplish this task: 

- [x] Expose only the resolvers that are needed by Portal to interact with the database. For now, I think that only the following resolvers should be exposed for querying. Note that this list can be extended as one work through this PR. 
    - [x]  Resolver to fetch all active applications. 
    - [x]  Resolvers to create / edit / delete application. 
    - [x]  Resolvers to create / edit / delete events. 
    - [x]  Resolver to create / edit / upsert profile. 
    - [x]  Resolver for users to check-in into an event. 

**Additional context**
- [Exposing certain Prisma actions for querying from GraphQL](https://prisma.typegraphql.com/docs/advanced/exposing-actions)

**Comment by spierceVR** [comment]
@DedsecKnight  I think this is basically done? Your PR #74 takes care of the middleware stuff.

**Comment by DedsecKnight** [comment]
Those are restrictions to only resolvers that Portal uses. We still need to hide the resolvers that are generated but not used. The initial plan was to apply the middlewares that I created in #74 to every other generated but not used resolvers, but I think that would be too tedious so I think it would be better if we just not expose those instead of applying restrictions.
