### ISSUE TITLE
[Feature] Login page

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#95]
**Describe new addition**
UI for login page needs to be implemented using React. 

**Task List**
 - [ ] Implement mockup (can be found in figma)
     - [ ] Supports both mobile and desktop view.  
     - [x] Should have ACM Portal logo and Log In button at minimum. 
         - [ ] **Stretch Goal**: Complete replication of the figma. 
 - [x] Navbar should be hidden in login page. 

**Additional context**
- [Current implementation of login page](https://github.com/acmutd/portal-next/blob/next/apps/portal/pages/index.tsx#L20-L26)
