### ISSUE TITLE
[Feature] ACM Member Check Logic

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#97]
**Describe new addition**
Currently, Portal does not have a mean to determine whether a user is an ACM member. Hence, a way to determine whether a user is an ACM member based on their participated events and semester program. 

**Task List**
 - [ ] ACM Member Criteria: 
     - [ ] Attend five ACM events in lifetime.
     - [ ] **Stretch**: Member of Projects, Research, TIP, Mentor Program
 - [ ] Introduce ACM Member Check Logic into portal-v2
     - [ ] Refactor database architecture if necessary. 
     - [ ] **Stretch**: Make it easy to change later on (in case the next exec team wants to change the criteria). 

**Additional context**
N/A
