### ISSUE TITLE
[Feature] Migrate data from portal-v1 database to portal-v2 database

### ISSUE THREAD

**Issue by DedsecKnight** [acmutd/portal-next#98]
**Describe new addition**
As portal-v2 uses a different database from portal-v1, all necessary data in portal-v1 database, including users' events participation and semester program participation. Following is one way to accomplish this feature: 

**Task List**
- [ ] Front-end
    - [x] Create a "Migrate Data" button in the home page
        - [ ] Upon clicking button, user will be shown their profile from old portal. 
            - [ ] Should show appropriate error message if profile cannot be found in old portal. 
        - [ ] User will be shown the data that will be migrated over to their new profile and allowed to confirm whether they want to initiate the migration
- [x] Back-end
    - [x] #117
    - [x] The migration process will involve copying event participation and cohort program from old profile to new profile.
        - [x] Create a mutation resolver that will take in user's netID, list of events, and list of cohort participation, and append event and program data into profile corresponding with netID.    
- [ ] **Optional**: Upon creating profile for the first time, user will be asked whether they want to migrate data from old portal to new one.  

**Additional context**
Above is but one way to accomplish this feature. If there is a potentially better approach or there is any way to improve the approach above, feel free to propose it in this issue thread.

**Comment by abhiamishra** [comment]
Is there a link to the DB schema of the current portal anywhere?

**Comment by abhiamishra** [comment]
https://docs.google.com/document/d/1dcm2uUonqIUqxEQXZMMO6IZj0aQhHpAY5VluCAlA8L0/edit?usp=sharing

**Comment by abhiamishra** [comment]
i am working on #117  - the query resolver

**Comment by DedsecKnight** [comment]
https://docs.google.com/document/d/1ceALy5FAH1qb-5wb3Rk29g3ZODH_Y4spK02hMM82MAY/edit

**Comment by abhiamishra** [comment]
Issues and comments mentioned in the meeting of January 16:

**Migration button disappearing**

- once data is migrated, the button should disappear

**How to handle the old events**

- either create a new table and have the user as having two arrays: one for new events and one for old events
- or add the old events into the new event table and its schema
- old dates can be identified in new dates with the use of a threshold

**What happens to migration script for event data?**

- not included in portal but included in portal documentation for future reference as a markdown file of some sorts
